---
apiVersion: v2
type: "application"
name: collabora-online
description: Collabora Online helm chart

version: 1.1.3
appVersion: "23.05.5.3.1"

home: "https://www.collaboraoffice.com/code/"
icon: "https://avatars0.githubusercontent.com/u/22418908?s=200&v=4"
sources:
  - "https://github.com/CollaboraOnline/online"
  - "https://github.com/CollaboraOnline/online/tree/master/docker"
  - "https://github.com/CollaboraOnline/online/tree/master/kubernetes/helm/collabora-online"

keywords:
  - "collabora-online"
  - "collabora"
  - "code"
  - "nextcloud"
  - "office"

maintainers:
  - name: "Klaus Erber"
    email: "k.erber@erber-freelance.de"
    url: "https://www.erber-freelance.de/"
  - name: "Martin MÃ¼ller"
    email: "martin.mueller@dataport.de"
    url: "https://dphoenixsuite.de"
  - name: "Geno"
    email: "geno+dev@fireorbit.de"
    url: "https://fireorbit.de"

annotations:
  artifacthub.io/images: |
    - name: collabora
      image: docker.io/collabora/code:23.05.5.3.1
    - name: nginx
      image: docker.io/nginx:1.25
    - name: twostoryrobot/simple-file-upload
      image: docker.io/twostoryrobot/simple-file-upload@sha256:547fc4360b31d8604b7a26202914e87cd13609cc938fd83f412c77eb44aa1cc4
