{{- if and .Values.dynamicConfig.enabled (not .Values.dynamicConfig.upload.enabled) (not .Values.dynamicConfig.existingConfigMap.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collabora-online.fullname" . }}-dynconfig
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.dynamicConfig.configuration | nindent 4 }}

{{- end}}
